### PR TITLE
Refactor ntpd to support multiple servers

### LINKED ISSUE #736: Need NTP Pool vendor name
https://github.com/boot2docker/boot2docker/blob/master/rootfs/rootfs/etc/rc.d/ntpd

Please see http://www.pool.ntp.org/vendors.html

### PR DESCRIPTION
**Pull request by tianon**
cc @nathanleclaire

I also tested manually setting my system clock to 1970-01-01, and this script as-is kicked me to the correct current time within a few iterations, but it might be worth splitting that out so the script blocks until the time is set, then backgrounds.  Hoping for some opinions on that. :smile:

Fixes #736

### CODE REVIEW

**Comment by nathanleclaire** [comment]
Interesting. I'll have to take a look on Monday.

**Comment by tianon** [comment]
... and with 4bd0c7d, this fixes #736 :smile: :cake:

**Comment by SvenDowideit** [comment]
LGTM - though I have not had time to set up a test

**Comment by nathanleclaire** [comment]
Also haven't really had time to test but the code looks reasonable and if you think it's good to merge I trust your judgment.

**Pull request merged**
