### PR TITLE
Update boot2docker build to get binaries from new URL

### PR DESCRIPTION
**Pull request by nathanleclaire**
cc @tianon 

Not fully rigged up yet, but should work once the endpoint is ready.

Signed-off-by: Nathan LeClaire <nathan.leclaire@gmail.com>

### CODE REVIEW

**Comment by tianon** [comment]
Whew -- just to cross-thread ALL THE THINGS, this is part of the transition for https://github.com/docker/docker/pull/31075.

**Comment by tianon** [comment]
Artifacts appear to be up, so I'm going to merge and get this building now.

**Comment by tianon** [comment]
Actually, can you update `README.md` too? (it has a reference to the current Docker version number)

**Comment by nathanleclaire** [comment]
Sure

**Comment by nathanleclaire** [comment]
Done

**Comment by nathanleclaire** [comment]
edit: had a conflict on kernel version

**Comment by tianon** [comment]
image

**Pull request merged**
