### PR TITLE
Add audio/sound support

### PR DESCRIPTION
**Pull request by xavriley**
I've been looking at adding audio support for about two weeks now and this PR is mainly to detail some of the issues I've encountered and to see whether they could be resolved. I realise this long winded way of discussing it is a bit pretentious and for that I'm sorry, but I wanted to document this against the project for anyone else who is interested in future. First though I want to make the case for adding sound to boot2docker.
## Why?

1) Docker now supports passing `--device /dev/snd:/dev/snd` #756
2) boot2docker is the _de facto_ dev tool for using Docker. As they depend on it for their dev machines it means that without audio a whole class of tools are ruled out of using Docker. (synthesizers, audio workstations, [guitar amp simulators](http://guitarix.org/))
3) Docker for desktop apps. People are already starting to use Docker for running web browsers as an added layer of security. YouTube isn't much fun without audio...
## Issues

> Why not just add the required packages to the Dockerfile and build a new iso?

The audio packages from the tinycore repo are not built for the 4.0.5 kernel. The current version for the `alsa-modules` package is 3.16.6 which means that the modules get installed into two different folders.

```
docker@boot2docker:~$ ls /lib/modules/
3.16.6-tinycore64/  4.0.5-boot2docker/
```

I think this means the required modules are not picked up by `depmod -a`. This means there's no `/proc/asound`. I'm not an expert on this so I may be missing something here.
## Solutions

1) Build an image with audio from version 3 of the Kernel

That's the approach I've gone for here https://github.com/boot2docker/boot2docker/compare/a270c71...xavriley:kernel3_with_audio and it should work in theory but I'm not able to login to the VM. I think that's a separate issue though...

2) Get tinycore to package tcz for the latest Kernel

This doesn't seem likely as I don't think they are a huge outfit and they'll want to stick to stable kernel versions I suspect. Also the `uname` of the latest b2d images is `4.0.5-boot2docker` which actually breaks the package manager for tinycore. It uses the $KERNEL string to determine whether to install 32bit or 64bit packages 

3) Package and self host the relevant libs in a `boot2docker` repo somewhere

Hosting a tinycore repo is as simple as having a webserver with static files. I suspect this could even be a github pages thing. Obviously that's a big effort/commitment but it would give an added layer of flexibility.

4) Something else?

I've tried several ways and none of them have worked so far. Any feedback or input would be much appreciated. Sorry if this PR is unhelpful.

### CODE REVIEW

**Comment by SvenDowideit** [comment]
I'm somewhat interested, as I too use b2d on a desktop. but yes, its not a big priority.

**Comment by tianon** [comment]
I'm not opposed to including the necessary kernel bits for this as modules, but I don't think I'm comfortable with including the userspace portions too -- can't those run in a container as long as the kernel modules are in place?

I know Jessie is a big fan of running `pulseaudio` specifically inside a container (see https://github.com/jfrazelle/dockerfiles/tree/master/pulseaudio).

**Comment by xavriley** [comment]
Yes Jessie's post on Docker on the desktop is awesome https://blog.jessfraz.com/post/docker-containers-on-the-desktop/ :)

Including the kernel bits would be a good start I think.

The reason I've had to include userspace tcz packages is for two reasons.

a) The host b2d instance needs to know about /dev/snd in order to be able to pass this on to any containers. I think this means the TC has to have alsa installed (or an equivalent) to pick up the sound card.

b) As I've tried to describe above, the tce package manager is broken for *some* packages in the b2d build. I tried several ways to install them on a vanilla b2d without success. Specifically, any packages (or deps) which list the kernel number *or* use the $KERNEL var to specify whether they should be 32 or 64 bit won't install.

I'm happy to investigate some other approaches if anyone has suggestions.

**Comment by sboily** [comment]
Hello, i'm also interested, not for desktop, but i need audio for my telecom dev plateform. I'm running linphone on docker but this is impossible with docker-machine.

**Comment by malex984** [comment]
AFAIK the standard boot2docker is missing a big chunk of VirtualBox Guest Additions and too many kernel modules. Therefore one has to devise his own image for desktop use. 

ps: It seems that `hyper_v.patch` is missing in your PR...

**Comment by cdenneen** [comment]
Has anyone gotten this to work with OSX? Using this or even the new docker for mac

**Comment by tianon** [comment]
Sorry for the long tail!

If someone wanted to recreate this with just the minimal necessary kernel changes to enable audio support, I'd be open to the idea (assuming it doesn't bloat the ISO size), but as I've noted above, this PR is not acceptable as-is (even if it were to be rebased/updated to match the changes made in the meantime).

Thanks for the contribution!

**Pull request closed without merging**
