### PR TITLE
use new 'daemon' command

### PR DESCRIPTION
**Pull request by gesellix**
Replace the deprecated `-d` command line flag with the new command name `daemon`.
See https://github.com/docker/docker/pull/13771 for details.

### CODE REVIEW

**Comment by josephpage** [comment]
:+1:

**Comment by tianon** [comment]
Awesome, thanks! :metal:

**Comment by gesellix** [comment]
:bow:

**Comment by md5** [comment]
This appears to have broken Unix socket connections to the Docker daemon.

I still see `-H unix://` in the command line used to call `docker daemon`, but it looks like that no longer causes the daemon to listen on `/var/run/docker.sock`:

```console
$ pgrep -d, docker | xargs ps -fp | cat
UID        PID  PPID  C STIME TTY          TIME CMD
root       892     1  0 03:35 ?        00:00:07 /usr/local/bin/docker daemon -D -g /var/lib/docker -H unix:// -H tcp://0.0.0.0:2376 --label provider=virtualbox --tlsverify --tlscacert=/var/lib/boot2docker/ca.pem --tlscert=/var/lib/boot2docker/server.pem --tlskey=/var/lib/boot2docker/server-key.pem -s aufs
```

This has broken `jwilder/nginx-proxy` and other containers that expect to connect via the Unix socket in their default configuration.

```console
docker@dev:~$ ls -l /var/run/docker.sock
srw-rw----    1 root     docker           0 Sep 12 03:35 /var/run/docker.sock
docker@dev:~$ fuser /var/run/docker.sock
docker@dev:~$ 
```

**Comment by md5** [comment]
I opened a PR in https://github.com/boot2docker/boot2docker/pull/1059

This probably also needs a bug opened against `docker/docker` for the regression of no longer supporting `unix://` as a value for `-H`...

**Comment by md5** [comment]
Nevermind... For whatever reason, `docker version` was saying this:

> Cannot connect to the Docker daemon. Is 'docker -d' running on this host?

But it doesn't appear to be an actual regression in the handing of `-H unix://`. Not sure what the actual cause was, but I saw a `docker daemon` pid running after a `docker-machine upgrade` and nothing was able to connect to the Unix socket. TLS connections from my host were working though.

**Pull request merged**
