### PR TITLE
Set CONFIG_CFQ_GROUP_IOSCHED=y and CONFIG_AUTOFS4_FS=m

### LINKED ISSUE #1189: modprobe autofs4
Hi,
I'm trying to run autofs module inside a boot2docker VM container.
It doesn't work because it cannot find the kernel module autofs4.
I tried loading it inside the boot2docker VM by doing sudo modprobe autofs4 but I got the error: 
modprobe: module autofs4 not found in modules.dep 
Any hint how to solve that ? Thanks

### PR DESCRIPTION
**Pull request by tianon**
Closes #1189

### CODE REVIEW

**Comment by tianon** [comment]
https://github.com/docker/docker/blob/2a540c18b69bebd7153ba87ffc91aade95ba2769/contrib/check-config.sh#L230 (`CFQ_GROUP_IOSCHED`)

**Comment by tianon** [comment]
Additionally: https://sources.debian.net/src/linux/4.6.4-1/debian/config/config/#L4973-L4976
```
##
## file: fs/autofs4/Kconfig
##
CONFIG_AUTOFS4_FS=m
```

**Comment by tianon** [comment]
cc @yosifkit

**Comment by yosifkit** [comment]
LGTM

**Pull request merged**
