### PR TITLE
Update AUFS to v4.1.13+-20160111

### PR DESCRIPTION
**Pull request by AkihiroSuda**
This should fix docker/docker#18180.
http://permalink.gmane.org/gmane.linux.file-systems.aufs.user/5345

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Closing and reopening the issue to trigger Travis again: `E: Failed to fetch http://httpredir.debian.org/debian/pool/main/libf/libfile-fcntllock-perl/libfile-fcntllock-perl_0.22-1+b1_amd64.deb  Error reading from server. Remote end closed connection [IP: 5.153.231.35 80]`

**Comment by tianon** [comment]
Don't we also need to apply the new patch?

**Comment by tianon** [comment]
Nevermind, just tested and it does appear that this is sufficient!  Very nice! :metal:

**Comment by tianon** [comment]
LGTM

**Comment by thaJeztah** [comment]
Oh, this is so great! Thanks @AkihiroSuda for all the work and research you did on this!

**Comment by klodoma** [comment]
@AkihiroSuda Maybe this seems like a very stupid question, but how can I install this on Ubuntu 14?

**Comment by AkihiroSuda** [comment]
@klodoma 
It will be officially available for Ubuntu 14.04 soon: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1533043

If you need it  immediately, you can build a custom kernel yourself
https://help.ubuntu.com/community/Kernel/Compile

If you are going to build a custom kernel, this patch should be enough, but I didn't test for Ubuntu 14.04:
https://github.com/sfjro/aufs4-linux/commit/f60d586b7b8cae42bacc603d192810db85278d3c

**Comment by AkihiroSuda** [comment]
@klodoma If you meant you just need to use the latest Boot2Docker on VirtualBox/VMWare/QEMU on your Ubuntu 14, just run `docker build -t boot2docker . && docker run --rm boot2docker > boot2docker.iso`.

**Comment by klodoma** [comment]
@AkihiroSuda thanks a lot! :) some things are confusing. I'll give it a try.

**Comment by klodoma** [comment]
@AkihiroSuda me again. Is there any guide how to run docker under Ubuntu, but not native, but in a VirtualBox? I think this could solve the issue with your ISO file, without the need to upgrade the local host. Right?

**Comment by AkihiroSuda** [comment]
$ docker-machine create -d virtualbox dm1
$ docker-machine stop dm1
$ cp -f your-iso-file ~/.docker/machine/machines/dm1/boot2docker.iso

**Comment by thaJeztah** [comment]
@klodoma @AkihiroSuda you can also use the `--virtualbox-boot2docker-url` option; https://docs.docker.com/machine/drivers/virtualbox/

**Comment by ches** [comment]
Apologies if this is a poor place to ask or if the release policy is explained somewhere I've overlooked, but—given the amount of interest in docker/docker#18180—are ISO releases of boot2docker ever made between Docker releases? If I could advise people that `docker-machine upgrade` is all that's needed to fix and move on with their day, that'd be swell!

Thanks everyone and especially @AkihiroSuda for your work.

**Comment by tianon** [comment]
There's a release candidate available at
https://github.com/tianon/boot2docker-legacy/releases/tag/v1.10.0-rc1 which
contains this fix. :+1:

**Pull request merged**
