### PR TITLE
Compile kernel modules for ipvsadm

### PR DESCRIPTION
**Pull request by glinton**
Include kernel modules required for `ipvsadm`

### CODE REVIEW

**Comment by tianon** [comment]
Cool, this seems sane. :+1:

Do you know if it has any other side effects or special edge cases we should be aware of?  As long as it doesn't have an effect on the standard use-case, I'm all for enabling random kernel modules. :smile:  (Something that might help answer this question would be to find out what Debian/Ubuntu's kernels set these particular values too. :pray: :innocent:)

**Comment by glinton** [comment]
There are no side effects or edge cases that I am aware of and both [Ubuntu 14.04](https://wiki.ubuntu.com/Kernel/Configs/SaucyToTrusty#line-2735) and [Debian 8](http://anonscm.debian.org/viewvc/kernel/releases/linux/3.16.7-ckt11-1%2Bdeb8u3~bpo70%2B1/debian/config/config?view=markup#l5797) have them turned on by default.

**Comment by tianon** [comment]
Excellent, thanks for doing the research! :heart: :+1:

LGTM

**Comment by greglearns** [comment]
I've been getting errors trying to run ipvsadm (and I've tried to find information on Google for hours now). What are the steps for getting ipvsadm working on a 2015 Macbook Pro running OS X El Capitan?

~/c/ipvs ❯❯❯ docker version
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:18:11 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 19:55:25 2016
 OS/Arch:      linux/amd64

**Comment by AkihiroSuda** [comment]
@greglearns Please try `--privileged`

**Comment by greglearns** [comment]
@AkihiroSuda Thank you, that worked. For others, this is what is required to run ipvsadm:

```docker run --privileged -it ubuntu /bin/bash```

```
root@35f9a493bf67:/# apt-get update && apt-get install ipvsadm -y && ipvsadm
root@35f9a493bf67:/# ipvsadm
```

Thank you!

**Pull request merged**
