### PR TITLE
Create CHANGELOG.md

### LINKED ISSUE #684: "Feature" request: Add a changelog
A changelog would be a very nice feature to have to make it easier to tell what's been fixed/changed/added to each release.

### PR DESCRIPTION
**Pull request by colinrymer**
This is a WIP commit; please do not merge until indicated by me (@colinrymer). The pull request was opened to get initial feedback and allow for commenting on the changelog while it's fleshed out.

Resolves #684

### CODE REVIEW

**Comment by SvenDowideit** [comment]
I'm very +1 :) @tianon

**Comment by thaJeztah** [comment]
I think the issue numbers should be changed to full (`https://....`) links to the GitHub issue tracker. I know *Github* does that automatically when viewing, but that won't work when reading the document locally. Also not sure what happens on forked repos (but that's less important).

I like this very much!

Oh, I think a note should be added to `CONTRIBUTING.md` to explain *who*, *when* and *how* the document should be updated

**Comment by SvenDowideit** [comment]
@colinrymer @tianon

**Comment by tianon** [comment]
https://github.com/boot2docker/boot2docker/issues/684#issuecomment-69224782

> That doesn't really explain what makes keeping this as a discrete file in the repo superior to just having the data available as it is today though, which is what I'm much more interested in a rationale for (especially since it's going to be me who has to maintain this extra document going forward).

**Comment by SvenDowideit** [comment]
mmm, I'm going to close this, as the person doing the releases doesn't really want to duplicate the work, and this PR is out of date.

feel free to reopen to convince @tianon otherwise :)

**Pull request closed without merging**
