### PR TITLE
Add VBoxService and use it for timesync!

### LINKED ISSUE #840: Boot2docker's VM time lagged behind the host's
Related to https://github.com/boot2docker/boot2docker/issues/290 (trigger b2d to run ntpdate on OSX/WIndows resume events)

I wonder if the above issue 290 has been fixed. I found that after sleeping and resuming my Mac, the time in boot2docker VM was 15min behind the host. I'm on the latest version (1.5.0).

### PR DESCRIPTION
**Pull request by tianon**
Fixes #840

### CODE REVIEW

**Comment by SvenDowideit** [comment]
oh yay

LGTM (er, ok, but i've not tested it)

**Comment by legal90** [comment]
@tianon Does `VBoxService` works fine in parallel with `ntpd` running in the VM? 
We are thinking about enabling internal time-sync mechanism in `parallels` driver for Docker Machine (https://github.com/Parallels/docker-machine-parallels/issues/26), but we afraid that it could cause some time jitter. Have anybody noticed/reported such problems?

**Comment by tianon** [comment]
I definitely haven't seen any reports of issues with it, but I'd be very, very interested in hearing results of more empirical testing. :smile:

**Comment by simonvanderveldt** [comment]
@tianon is this fix actually working for you/have you had any new reports about it not working?
I couldn't find any new issues on it, but for me it still isn't working correctly. I still have situations where the time is too much out of sync which means certain signed requests fail to work.

One obvious thing is what @legal90 mentions, that both ntpd as well as virtualbox timesync are now being used, which will probably result in issues. Would it be possible to get rid of the ntpd?

**Pull request merged**
