### PR TITLE
Add missing configurations for VMware

### LINKED ISSUE #1369: Persistent partition does not exist on VMware Fusion with v18.09.1-rc1
```terminal.sh-session
$ docker-machine create --driver vmwarefusion --vmwarefusion-no-share --vmwarefusion-boot2docker-url https://github.com/boot2docker/boot2docker/releases/download/v18.09.1-rc1/boot2docker.iso default3
Running pre-create checks...
(default3) Boot2Docker URL was explicitly set to "https://github.com/boot2docker/boot2docker/releases/download/v18.09.1-rc1/boot2docker.iso" at create time, so Docker Machine cannot upgrade this machine to the latest version.
Creating machine...
(default3) Boot2Docker URL was explicitly set to "https://github.com/boot2docker/boot2docker/releases/download/v18.09.1-rc1/boot2docker.iso" at create time, so Docker Machine cannot upgrade this machine to the latest version.
(default3) Downloading /Users/norio/.docker/machine/cache/boot2docker.iso from https://github.com/boot2docker/boot2docker/releases/download/v18.09.1-rc1/boot2docker.iso...
(default3) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
(default3) Creating SSH key...
(default3) Creating VM...
(default3) Creating disk '/Users/norio/.docker/machine/machines/default3/default3.vmdk'
(default3) Virtual disk creation successful.
(default3) Starting default3...
(default3) Waiting for VM to come online...
Error creating machine: Error in driver during machine creation: exit status 255
$ docker-machine ssh default3
   ( '>')
  /) TC (\   Core is distributed with ABSOLUTELY NO WARRANTY.
 (/-_--_-\)           www.tinycorelinux.net

docker@boot2docker:~$ mount
tmpfs on / type tmpfs (rw,relatime,size=911740k)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,mode=600,ptmxmode=000)
tmpfs on /dev/shm type tmpfs (rw,relatime)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)
cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,relatime,net_cls)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_prio type cgroup (rw,relatime,net_prio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,relatime,hugetlb)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,relatime,pids)
tmpfs on /var/lib/docker type tmpfs (rw,relatime,size=911740k)
```

### PR DESCRIPTION
**Pull request by norio-nomura**
fixes #1369

### CODE REVIEW

**Comment by tianon** [comment]
Is this the minimal set necessary, or is this simply enabling more flags and one of them happens to do the trick? (How much testing has this had?)

**Comment by norio-nomura** [comment]
The minimal set is `CONFIG_VMWARE_PVSCSI` for #1369 (maybe #1368 too).
But I think all adding configs are needs for running on VMware.

- [VMWARE_BALLOON](https://cateee.net/lkddb/web-lkddb/VMWARE_BALLOON.html)
> This is VMware physical memory management driver which acts like a "balloon" that can be inflated to reclaim physical pages by reserving them in the guest and invalidating them in the monitor, freeing up the underlying machine pages so they can be allocated to other guests. The balloon can also be deflated to allow the guest to use more physical memory.
- [VMWARE_PVSCSI](https://cateee.net/lkddb/web-lkddb/VMWARE_PVSCSI.html)
> This driver supports VMware's para virtualized SCSI HBA
- [VMWARE_VMCI_VSOCKETS](https://cateee.net/lkddb/web-lkddb/VMWARE_VMCI_VSOCKETS.html) (depends on [VSOCKETS](https://cateee.net/lkddb/web-lkddb/VSOCKETS.html))
> This module implements a VMCI transport for Virtual Sockets.
Enable this transport if your Virtual Machine runs on a VMware hypervisor.

> How much testing has this had?

I confirmed that .iso including this change works like [v18.06.1-ce](https://github.com/boot2docker/boot2docker/releases/tag/v18.06.1-ce) do.

**Comment by norio-nomura** [comment]
Information about Linux driver for VMware: https://kb.vmware.com/s/article/2073804

**Comment by unsignedint** [comment]
Sorry, I am new to this project.. can someone explain how to actually build this PR (or boot2docker in general)? Thanks :)

**Comment by frol** [comment]
FYI there is also PR #1372, which partially overlaps with the listed modules.

**Comment by frol** [comment]
> How much testing has this had?

I have combined the kernel options from this and #1372 PRs and built an image which successfully run on my VMware ESXi server and detected the persistent hard drive (thus, my issue #1368 will be resolved with this PR) and also successfully passed my automatic stress-testing suite (it uses quite a few of Docker features and some extra Cgroup capabilities).

@unsignedint To build `boot2docker.iso`, run these two commands:

```
docker built -t boot2docker .
docker run --rm boot2docker > boot2docker.iso
```

Here is the image I have built: https://drive.google.com/file/d/1uIeMp5UE6xswZdoU4Xn7nOAvsJ-cefix/view?usp=sharing

**Comment by norio-nomura** [comment]
Thanks! 🙏

**Pull request merged**
