### PR TITLE
Adjust to allow "--userns-remap=default" to work out-of-the-box

### LINKED ISSUE #1134: `--userns-remap` feature not supported?
When I add `--userns-remap=defaut` to `EXTRA_ARGS` in `/var/lib/boot2docker/profile`, then `docker-machine start ...` reports:

`Unable to verify the Docker daemon is listening: Maximum number of retries (10) exceeded`

When I stop docker with `sudo /etc/init.d/docker stop` and then run the command manually, I get a fatal error:

```
docker@default:~$ sudo /usr/local/bin/docker daemon -D -g /var/lib/docker -H unix:// -H tcp://0.0.0.0:2376 --label provider=vmwarefusion --tlsverify --tlscacer
t=/var/lib/boot2docker/ca.pem --tlscert=/var/lib/boot2docker/server.pem --tlskey=/var/lib/boot2docker/server-key.pem -s aufs --userns-remap=default
UEBU[0000] Trusting certs with subjects: [010
tailee] 
DEBU[0000] docker group found. gid: 100                 
DEBU[0000] Server created for HTTP on unix (/var/run/docker.sock) 
DEBU[0000] Server created for HTTP on tcp (0.0.0.0:2376) 
FATA[0000] Error starting daemon: Error during "dockremap" user creation: Error adding group "dockremap": Cannot add group; no groupadd/addgroup binary found 
```

But there is an `addgroup` binary:

```
docker@default:~$ which addgroup
/usr/sbin/addgroup
```

If I add my own group and user manually, and try to use those, I get a different error:

```
docker@default:~$ sudo addgroup -g 20 osx_staff
docker@default:~$ sudo adduser -G osx_staff -SDHu 501 osx_tailee
docker@default:~$ sudo /usr/local/bin/docker daemon -D -g /var/lib/docker -H unix:// -H tcp://0.0.0.0:2376 --label provider=vmwarefusion --tlsverify --tlscacer
t=/var/lib/boot2docker/ca.pem --tlscert=/var/lib/boot2docker/server.pem --tlskey=/var/lib/boot2docker/server-key.pem -s aufs --userns-remap=501:20
UEBU[0000] Trusting certs with subjects: [010
tailee] 
DEBU[0000] docker group found. gid: 100                 
DEBU[0000] Server created for HTTP on unix (/var/run/docker.sock) 
DEBU[0000] Server created for HTTP on tcp (0.0.0.0:2376) 
INFO[0000] User namespaces: ID ranges will be mapped to subuid/subgid ranges of: osx_tailee:osx_staff 
FATA[0000] Error starting daemon: Can't create ID mappings: open /etc/subuid: no such file or directory 
```

I am not a linux guru. I tried reading the docker docs and linux man page for `subuid`, and came away less than enlightened.

What do I need to do to start using the new user namespace feature of docker 1.10 on OS X with `docker-machine` and `boot2docker`? I just want files written to volumes I share from my mac into a container to have the same owner and group as on my OS X machine (uid 501, gid 20).

### PR DESCRIPTION
**Pull request by tianon**
Closes #1134
Closes #1142

### CODE REVIEW

**Comment by tianon** [comment]
cc @yosifkit

**Comment by yosifkit** [comment]
LGTM

**Comment by tianon** [comment]
Tested locally, working really, really well.

**Comment by tianon** [comment]
Docker automatically uses `/var/lib/docker/165536.165536` when this is enabled, so we don't need to muck with `/var/lib/docker` either (which I also tested). :+1:

**Comment by QianJin2013** [comment]
+1

**Pull request merged**
