### PR TITLE
Re-add support for the "LsiLogic SAS Controller" in VirtualBox

### LINKED ISSUE #1375: oracle vm box; no access to SAS  Storage Devices since boot2docker >= 18.09
With boot2docker 18.06 I can access SAS Storage devices defined in Oracle VM BOX.
This is not possible with boot2docker >= 18.09

Is there a way to change this?

### PR DESCRIPTION
**Pull request by tianon**
Fixes #1375

### CODE REVIEW

**Comment by tianon** [comment]
@AnselmD would you mind giving this a try to make sure it works? :pray: :heart:

(In case you need it, a pre-built ISO of this PR is available at https://gist.github.com/tianon/65c4f30046e2dca4ef2641755b2b3465 -- direct ISO link at https://gist.github.com/tianon/65c4f30046e2dca4ef2641755b2b3465/raw/4773dea59e426a78b855b54656fcb1e7bf712856/boot2docker.iso which should be usable via `--virtualbox-boot2docker-url` in `docker-machine` although you already seem pretty familiar with all that. :+1:)

**Comment by AnselmD** [comment]
@tianon Great, now i am able to see the SAS disk (i used --virtualbox-boot2docker-url with docker-machine and add the SAS disk afterwards in the oracle vm box). But when i starts the virtual machine a second time (even without adding a SAS controller), i am getting a warning:
2019-01-22 22_00_53-boot2dockertest3 running - oracle vm virtualbox

Can i ignore this?

**Comment by tianon** [comment]
Yeah, that's expected -- the VM is trying to be more aggressive about
ensuring you have adequate entropy available.

The disk is still working after a reboot?

**Comment by AnselmD** [comment]
> 
> Yeah, that's expected -- the VM is trying to be more aggressive about ensuring you have adequate entropy available. 

:+1:

But I do not mean the havged (i dislike to have too less entropy, this can make a lot of trouble). I mean the 
'aufs' is not a supported storage driver...

>The disk is still working after a reboot?

I think so, but i will again check it tomorrow and give you feedback.

**Comment by tianon** [comment]
Ah, regarding AUFS, see the following warning on the 18.09 release notes (https://github.com/boot2docker/boot2docker/releases/tag/v18.09.1):

> **Warning:** the AUFS storage driver is deprecated in boot2docker and AUFS support is removed in 18.09+. You can continue with AUFS in boot2docker 18.06.x, but it is recommended to reset your disk image before updating to 18.09+. **See #1326 for more discussion.**

**Pull request merged**
