### PR TITLE
wait for disks to actually exist, closes #793

### LINKED ISSUE #793: Boot2docker fails to properly format partitions
**Problem**

boot2docker fails to properly format partitions on some disks

**Solution**

When you write the magic string "boot2docker, please format-me" on a
 virtual disk, on first boot, it will partition, and then lay down a
 filesystem.  If the back-end device (or driver) is slow to respond, the
 formatting step will sometimes fail.  We should harden the init scripts
 to retry on failure a few times to harden the bootstrapping logic.  If you
 use QEMI/KVM with the virt-io driver, this is reproducible.

### PR DESCRIPTION
**Pull request by nlf**
pretty self explanatory, just wait for the block devices to exist before attempting to format them

### CODE REVIEW

**Comment by SvenDowideit** [comment]
depressing - @tianon ?

**Comment by SvenDowideit** [comment]
@nlf , I'd feel more comfortable with a non-inifinite loop on failure.....

**Comment by nlf** [comment]
that's fair, i'll add a timeout

**Comment by tianon** [comment]
The proposed solution is pretty self-explanatory, but I don't think I understand enough about the problem it's fixing to comment -- can you elaborate? :confused:

I thought this was the entire point of the `partprobe` addition -- forcing the kernel to synchronously update based on the partition changes.

**Comment by nlf** [comment]
with a slow disk, partprobe is sometimes not enough. when booting with xhyve, for example, the partition doesn't become available immediately after the `partprobe` and this loop is necessary.

**Comment by dhiltgen** [comment]
I see the same problem using the KVM hypervisor.  On a heavily loaded system, sometimes it'll fail to partition and mount the disks properly.

**Comment by tianon** [comment]
Ok, I suppose this is good enough for now -- I'm still really curious whether Debian, etc have the same issue, and how they get around it (although perhaps in this case it'd just be debian-installer that'd be affected, since it has to do with partitioning).

LGTM

**Pull request merged**
