### PR TITLE
Update to Linux 4.0.1

### LINKED ISSUE #861: Bump kernel to 4.0
Could you please bump the kernel to 4.0? `kmem` leaks in cgroup were fixed ([here are more details](https://github.com/docker/docker/issues/6479#issuecomment-97503551))

### PR DESCRIPTION
**Pull request by tianon**
Fixes #861

### CODE REVIEW

**Comment by tianon** [comment]
```console
docker@boot2docker:~$ docker run --rm hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from hello-world
a8219747be10: Pull complete 
91c95931e552: Already exists 
hello-world:latest: The image you are pulling has been verified. Important: image verification is a tech preview feature and should not be relied on to provide security.
Digest: sha256:aa03e5d0d5553b4c3473e89c8619cf79df368babd18681cf5daeb82aab55838d
Status: Downloaded newer image for hello-world:latest
Hello from Docker.
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (Assuming it was not already locally available.)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

For more examples and ideas, visit:
 http://docs.docker.com/userguide/
docker@boot2docker:~$ docker info
Containers: 0
Images: 2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: tmpfs
 Dirs: 2
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 4.0.1-tinycore64
Operating System: Boot2Docker 1.6.0 (TCL 5.4); master : 8c82162 - Sun May  3 14:53:48 UTC 2015
CPUs: 1
Total Memory: 3.86 GiB
Name: boot2docker
ID: XMFD:M5KP:PEJK:UKTZ:LILD:34AY:TE5M:6AFN:2KJZ:PAPS:G2VA:FE2T
Debug mode (server): true
Debug mode (client): false
Fds: 14
Goroutines: 19
System Time: Sun May  3 14:58:29 UTC 2015
EventsListeners: 0
Init SHA1: 9145575052383dbf64cede3bac278606472e027c
Init Path: /usr/local/bin/docker
Docker Root Dir: /var/lib/docker
```

**Comment by tianon** [comment]
cc @frol :smile:

**Comment by frol** [comment]
@tianon You are awesome! Thanks!

**Comment by thaJeztah** [comment]
Nice! So overlay and btrfs support as well?

**Comment by SvenDowideit** [comment]
yup, we've had overlay and btrfs for a while, but we've not made is obvious.

very yay LGTM

**Comment by thaJeztah** [comment]
Hm, sounds like I should be pestering DigitalOcean to add b2d as an option :)

**Comment by tianon** [comment]
Oh jeez, please no. :fearful:

**Comment by thaJeztah** [comment]
@tianon no worries, I won't, was just fooling around (although I hope they have a 4.x kernel soon, haven't checked recently) :smiley:

**Comment by tianon** [comment]
:sweat_smile: :+1: :heart:

**Pull request merged**
