### PR TITLE
VBox guest additions

### PR DESCRIPTION
**Pull request by steeve**
This is a PR in response to #282.
It adds ~400kb to the unpacked system.
Please discuss wether vboxsf are a good option of not in #282, not here.

Add a shared folder to the VM:

```
$ boot2docker stop
$ VBoxManage sharedfolder add boot2docker-vm -name home -hostpath $HOME
```

Now mount the folder inside the VM:

```
$ boot2docker up
$ boot2docker ssh "sudo modprobe vboxsf && mkdir -p $HOME && sudo mount -t vboxsf home $HOME"
```

You can now run `docker -v` transparently as long as the volume is inside `$HOME`.

A test ISO based on 0.7 is at https://dl.dropboxusercontent.com/u/12014139/boot2docker.iso

### CODE REVIEW

**Comment by nathan-zhu** [comment]
hi, any news for this, i'm use docker1.7 but still have same problem. please help.

**Comment by thaJeztah** [comment]
@nathan-zhu no single solution yet. The performance issue isn't related to Docker itself, just the VBox guest additions. You can find some alternative approaches in the discussion above though, that might help in your situation.

However, the Docker 1.7 "experimental build" offers "Volume Drivers" (see https://github.com/docker/docker/blob/master/experimental/plugins_volume.md), which could potentially open up some possibilities (for example, see https://github.com/docker/docker/issues/13420#issuecomment-111346689)

**Comment by mattes** [comment]
@nathan-zhu Check out https://github.com/synack/docker-rsync. It's pretty experimental though.

**Comment by gansbrest** [comment]
@nathan-zhu I guess I still have to recommend Hodor (https://github.com/gansbrest/hodor) for now for fast bidirectional sync through Unison.

**Comment by ehernandez-xk** [comment]
Hi, 
What is the status of this? because I have the problem with the following configuration:

Windows 7
I have a custom boot2docker form 1.11.1 version
VirtualBox 5.0.16
Vagrant 1.8.5

```
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attemped was:

set -e
mount -t vboxsf -o uid=`id -u docker`,gid=`getent group docker | cut -d: -f3` b5
973a5087 /var/lib/docker/docker_1472079332_51007
mount -t vboxsf -o uid=`id -u docker`,gid=`id -g docker` b5973a5087 /var/lib/doc
ker/docker_1472079332_51007

The error output from the command was:

mount: mounting b5973a5087 on /var/lib/docker/docker_1472079332_51007 failed: Pr
otocol error
```

Do you have an example to use it on windows? I'm using Vagrant and docker as a provider.

**Comment by ehernandez-xk** [comment]
When I run `mount`manually I get this message.

```
-sh: getent: not found
gid= requires an argument (i.e. gid==<arg>)
mount: mounting vagrant on /vagrant failed: Protocol error
```

**Comment by ehernandez-xk** [comment]
Thank you @dduportal

**Pull request closed without merging**
