### PR TITLE
Add SHA256 verification to our VBoxGuestAdditions.iso fetching

### PR DESCRIPTION
**Pull request by tianon**
I officially dedicate this PR to @nathanleclaire.

image

(someday I hope to be a unicorn, just like this little rhino does)

### CODE REVIEW

**Comment by tianon** [comment]
Relevant build output:
```console
...
Step 27 : ENV VBOX_VERSION 5.1.10
 ---> Using cache
 ---> 12df3a63fc34
Step 28 : ENV VBOX_SHA256 29fa0af66a3dd273b0c383c4adee31a52061d52f57d176b67f444698300b8c41
 ---> Using cache
 ---> ff3845024065
Step 29 : RUN set -x &&         mkdir -p /vboxguest &&     cd /vboxguest &&         curl -fL -o vboxguest.iso http://download.virtualbox.org/virtualbox/${VBOX_VERSION}/VBoxGuestAdditions_${VBOX_VERSION}.iso &&     echo "${VBOX_SHA256} *vboxguest.iso" | sha256sum -c - &&     7z x vboxguest.iso -ir'!VBoxLinuxAdditions.run' &&     rm vboxguest.iso &&         sh VBoxLinuxAdditions.run --noexec --target . &&     mkdir amd64 && tar -C amd64 -xjf VBoxGuestAdditions-amd64.tar.bz2 &&     rm VBoxGuestAdditions*.tar.bz2 &&         KERN_DIR=/linux-kernel/ make -C amd64/src/vboxguest-${VBOX_VERSION} &&     cp amd64/src/vboxguest-${VBOX_VERSION}/*.ko $ROOTFS/lib/modules/$KERNEL_VERSION-boot2docker/ &&         mkdir -p $ROOTFS/sbin &&     cp amd64/lib/VBoxGuestAdditions/mount.vboxsf amd64/sbin/VBoxService $ROOTFS/sbin/ &&     mkdir -p $ROOTFS/bin &&     cp amd64/bin/VBoxClient amd64/bin/VBoxControl $ROOTFS/bin/
 ---> Running in e3fd9974b787
+ mkdir -p /vboxguest
+ cd /vboxguest
+ curl -fL -o vboxguest.iso http://download.virtualbox.org/virtualbox/5.1.10/VBoxGuestAdditions_5.1.10.iso
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 56.6M  100 56.6M    0     0  1496k      0  0:00:38  0:00:38 --:--:-- 2140k
+ echo 29fa0af66a3dd273b0c383c4adee31a52061d52f57d176b67f444698300b8c41 *vboxguest.iso
+ sha256sum -c -
vboxguest.iso: OK
+ 7z x vboxguest.iso -ir!VBoxLinuxAdditions.run

7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
p7zip Version 9.20 (locale=C,Utf16=off,HugeFiles=on,8 CPUs)

Processing archive: vboxguest.iso
...
```

**Comment by nathanleclaire** [comment]
Nice.  Yeah I wish they distributed via SSL but better than nothing.  And I love the GIF ❤️

**Comment by nathanleclaire** [comment]
LGTM

**Comment by tianon** [comment]
https://github.com/boot2docker/boot2docker/commit/2a30a73b4a892ee60150606a91f2b59c1b2972ec updates the URL in this comment to https://www.virtualbox.org/download/hashes/5.1.10/SHA256SUMS so it's HTTPS :metal:

**Comment by nathanleclaire** [comment]
🤘 👨 🤘

**Pull request merged**
