### PR TITLE
Add "CONFIG_USB_SERIAL" back

### LINKED ISSUE #1361: USB serial device not working since v18.09
Since v18.09 the USB device sharing for serial devices is not working anymore (which for me is **the reason** to use docker-machine). 

I am not sure what the cause for this is, but to me it looks like either 
 a. USB serial device support is deactivated in the kernel?
 b. kernel modules are not installed by default

Its hard for me to debug any further because as described in #1360 I cannot install any programs that could help me digging deeper.

### Steps to reproduce
0. Create VM with latest boot2docker image: `$ docker-machine create --driver virtualbox default` 
1. Stop VM `$ docker-machine stop`
2. Enable USB support in the boot2docker VM settings, and add filter for USB serial adapter (For reproducing the bug a USB serial adapter is required on the VM Host machine)
3. Start VM `$ docker-machine start`
4. log in to boot2docker VM: `$ docker-machine ssh`
5. First thing to notice that something is broken is that the *usual* device symlink for the USB serial adapter does not exist:
   ```
   docker@default:~$ ls -l /dev/ttyUSB*
   ls: /dev/ttyUSB*: No such file or directory
   ```
6. Listing the usb devices in `/dev/bus/usb/001/` shows that the USB device was enumerated 

### Expected behavior
Following the same steps as above on v18.06 shows the expected behavior:

0. Create VM with boot2docker v18.06: `$ docker-machine create --driver virtualbox --virtualbox-boot2docker-url https://github.com/boot2docker/boot2docker/releases/download/v18.06.1-ce/boot2docker.iso default1806`
1. Stop VM: `docker-machine stop default1806`
2. Enable USB support in the boot2docker VM settings, and add filter for USB serial adapter (For reproducing the bug a USB serial adapter is required on the VM Host machine)
3. Start VM `$ docker-machine start default1806`
4. log in to boot2docker VM: `$ docker-machine ssh default1806`
5. Here the device symlink exists under `/dev/ttyUSB0`:
   ```
   docker@default1806:~$ ls -l /dev/ttyUSB0
   crw-rw----    1 root     staff     188,   0 Nov 25 22:04 /dev/ttyUSB0
   ```
6. (Looking into the the bus/usb subsystem is not here needed as the symlink already shows that the device was found and enumerated)
7. getting the Options for the tty device via stty is successful:
   ```
   docker@default1806:~$ stty -F /dev/ttyUSB0
   speed 9600 baud; line = 0;
   intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R; werase = ^W; lnext = ^V; flush = ^O;
   min = 1; time = 0;
   -brkint -imaxbel
   ```

### System info

Operating System: OSX Mojave 10.14.1

```
$ docker --version
Docker version 18.09.0, build 4d60db4

$ docker-machine --version
docker-machine version 0.16.0, build 702c267f
```

### PR DESCRIPTION
**Pull request by tianon**
Fixes #1361

### CODE REVIEW

**Comment by tianon** [comment]
cc @StefanD986 -- can you give this a test?  it builds successfully, but I don't have any USB serial devices to test it with

You can find a test ISO in https://gist.github.com/tianon/e49ce1683229d9a4356f6d065a2ec451 (should be usable directly via `--DRIVER-boot2docker-url https://gist.github.com/tianon/e49ce1683229d9a4356f6d065a2ec451/raw/ec72575a3aa4e7f6b3e4885358c414156f1e8378/boot2docker.iso`).

**Comment by StefanD986** [comment]
Hmm, not quite. I only was able to do a really quick check, but also with the new ISO the device file is not created.

One thing that I noticed is that the old 18.06 version also has a kernel module `usbserial` which is loaded, whereas the in 18.09 (and also in the ISO linked above) the `usbserial` module seems to be missing.

`lsmod` from new ISO:
```
docker@test:~$ lsmod
Module                  Size  Used by    Tainted: G  
ipt_MASQUERADE         16384  1 
nf_nat_masquerade_ipv4    16384  1 ipt_MASQUERADE
xfrm_user              32768  1 
iptable_nat            16384  1 
nf_nat_ipv4            16384  1 iptable_nat
xt_addrtype            16384  2 
iptable_filter         16384  1 
xt_conntrack           16384  1 
nf_nat                 24576  2 nf_nat_masquerade_ipv4,nf_nat_ipv4
br_netfilter           20480  0 
bridge                106496  1 br_netfilter
stp                    16384  1 bridge
llc                    16384  2 bridge,stp
overlay                61440  0 
vboxsf                 36864  1 
ext4                  536576  1 
mbcache                16384  1 ext4
jbd2                   86016  1 ext4
squashfs               32768  3 
vboxguest             212992  2 vboxsf
```

`lsmod` from v18.06

```
docker@default1806:~$ lsmod
Module                  Size  Used by    Tainted: G  
ipt_MASQUERADE         16384  1 
nf_nat_masquerade_ipv4    16384  1 ipt_MASQUERADE
nf_conntrack_netlink    28672  0 
iptable_nat            16384  1 
nf_conntrack_ipv4      16384  2 
nf_defrag_ipv4         16384  1 nf_conntrack_ipv4
nf_nat_ipv4            16384  1 iptable_nat
xt_addrtype            16384  2 
xt_conntrack           16384  1 
nf_nat                 20480  2 nf_nat_masquerade_ipv4,nf_nat_ipv4
nf_conntrack           69632  6 nf_nat_masquerade_ipv4,nf_conntrack_netlink,nf_conntrack_ipv4,nf_nat_ipv4,xt_conntrack,nf_nat
br_netfilter           20480  0 
bridge                 86016  1 br_netfilter
stp                    16384  1 bridge
llc                    16384  2 bridge,stp
ipv6                  286720 15 bridge,[permanent]
vboxsf                 32768  1 
joydev                 20480  0 
cpufreq_conservative    16384  0 
cpufreq_userspace      16384  0 
cpufreq_powersave      16384  0 
ftdi_sio               45056  0 
usbserial              24576  1 ftdi_sio
squashfs               32768  0 
pcspkr                 16384  0 
video                  32768  0 
backlight              16384  1 video
battery                16384  0 
ac                     16384  0 
loop                   24576  0 
intel_agp              16384  0 
intel_gtt              20480  1 intel_agp
agpgart                32768  2 intel_agp,intel_gtt
i2c_piix4              16384  0 
vboxguest             184320  2 vboxsf
e1000                  94208  0 
```

**Comment by tianon** [comment]
`usbserial` is the generic module that this PR currently adds (if you do `modprobe usbserial` in this new ISO I've provided, it should load successfully).  Looking at your output, I think `ftdi_sio` is the real provider of `/dev/ttyUSB0` for your device (which does so via the generic USB serial interface provided by `usbserial`), so we'll need to enable whatever kernel configuration provides that as well.

**Comment by tianon** [comment]
Updated to copy all of Debian's relevant `CONFIG_USB_SERIAL*` bits directly (minus one that has other prereqs); new ISO at https://gist.github.com/tianon/e49ce1683229d9a4356f6d065a2ec451 now.

(usable via `--DRIVER-boot2docker-url https://gist.github.com/tianon/e49ce1683229d9a4356f6d065a2ec451/raw/0e65aa9f0728836a0d0ac95b7e3c78c98beebe4e/boot2docker.iso`)

**Comment by StefanD986** [comment]
Yes, this fixes it for me with my FTDI adapter.
Now the `usbserial` and `ftdi_sio` module are automatically loaded.

Thanks a lot!

P.S. would be nice to have an official release with that fix implemented soon.

**Comment by tianon** [comment]
Any idea why Debian wouldn't have included that one in their builds?

**Comment by StefanD986** [comment]
AFAIK, it is actually included in Debian, however it is not part of the`CONFIG_USB_SERIAL_*` group. (I can only speculate, but I guess this is for historical reasons? The `cdc_acm` module documentation says its for usb modems, but its seems nowadays it is also used by some USB to serial adapters)

The relevant lines I can find in the debian config are:
https://salsa.debian.org/kernel-team/linux/blob/master/debian/config/config#L4967
and
https://salsa.debian.org/kernel-team/linux/blob/master/debian/config/config#L4930

**Pull request merged**
