### PR TITLE
add docker-volume-vsphere suppport again

### PR DESCRIPTION
**Pull request by qxo**
ref:
https://github.com/boot2docker/boot2docker/issues/1270
https://github.com/boot2docker/boot2docker/pull/1275

### CODE REVIEW

**Comment by frol** [comment]
FYI there is also PR #1370, which partially overlaps with the listed modules.

**Comment by jkldgoefgkljefogeg** [comment]
`docker-machine create --driver vmwarevsphere` created VM without eth0 interface with boot2docker v18.09.0, fixed by this
`--vmwarevsphere-boot2docker-url https://github.com/boot2docker/boot2docker/releases/download/v18.09.1-rc1/boot2docker.iso`

**Comment by jkldgoefgkljefogeg** [comment]
What is the difference between value `m` and `y`?

VMWARE_VMCI_VSOCKETS depends on: CONFIG_VSOCKETS && CONFIG_VMWARE_VMCI

https://cateee.net/lkddb/web-lkddb/VMWARE_VMCI_VSOCKETS.html

**Comment by tianon** [comment]
Closed in favor of #1370 (which is now merged). :+1:

**Pull request closed without merging**
