### PR TITLE
Add support virtio-9p

### PR DESCRIPTION
**Pull request by zchee**
[docker-machine-driver-xhyve](https://github.com/zchee/docker-machine-driver-xhyve/commit/1820ebd7cfe0f44504f8386fe7662a9fc21fe0b6) implemented `virtio-9p` folder sharing for `xhyve` use [lib9p](https://github.com/jceel/lib9p).
Original sources by [jceel/xhyve](https://github.com/jceel/xhyve).

This implements need enable `9p` on kernel_config.
Please let us know what you think.

/cc @tianon

### CODE REVIEW

**Comment by tianon** [comment]
I'm guessing it's negligible, but do you have a before/after on ISO size?

I'm totally +1 otherwise!

**Comment by zchee** [comment]
@tianon Thanks reply :)

I do not yet build `1.10.1`, checked version is `1.10.0`.

Result,
```bash
> ls -l boot2docker.iso
-rw-r--r-- 1 zchee staff 33554432 Feb  5 05:51 boot2docker.iso
~
> ls -l boot2docker-virt9p.iso
-rw-r--r-- 1 zchee staff 33554432 Feb 11 00:12 boot2docker-virt9p.iso

> stat boot2docker.iso
device  16777223
inode   18445056
mode    33188
nlink   1
uid     501
gid     20
rdev    0
size    33554432
atime   1455317480
mtime   1454619117
ctime   1455317438
blksize 4096
blocks  65536
link

> stat boot2docker-virt9p.iso
device  16777223
inode   18445033
mode    33188
nlink   1
uid     501
gid     20
rdev    0
size    33554432
atime   1455317467
mtime   1455117166
ctime   1455317408
blksize 4096
blocks  65536
link
```

It seems completely unchanged the size.(I'm surprised...)

and, Here is patched iso download link.
https://github.com/zchee/boot2docker-legacy/releases/tag/v1.10.0-virtio-9p

**Comment by tianon** [comment]
Nice, that's perfect! LGTM

We have yet to dig in to why things like this don't increase the ISO size, but it's common. :smile:

**Comment by zchee** [comment]
@tianon Thanks fast response!!
:tada: 
I'm looking forward to next release version :)

**Pull request merged**
