### PR TITLE
Update to Linux 4.1

### PR DESCRIPTION
**Pull request by tianon**
cc @frapposelli @legal90 @phusl -- anything objections to making this move?  Any additional changes we'll need to make that you're aware of?

### CODE REVIEW

**Comment by tianon** [comment]
(Justification is at https://www.kernel.org/ -- 4.0 is no longer supported, and 4.1 is "stable".)

**Comment by tianon** [comment]
A follow question would be whether 4.2 would be possible/better? :wink:

**Comment by legal90** [comment]
@tianon On the Parallels Tools side we don't have any concerns about Linux kernel 4.1
I've just checked this PR with the latest build of Parallels tools (https://github.com/boot2docker/boot2docker/pull/1051) and it works fine.
So, upgrade to 4.1 is OK for us :+1: 

However, we've found that Parallels Tools could not be built  on Linux kernel 4.2. :disappointed: 
We are working on it and it should be fixed in Parallels Tools in October-November 2015. 
Please, delay the upgrade to 4.2 for now if possible.

**Comment by frapposelli** [comment]
@tianon I'm in the process of moving to `open-vm-tools` 10.x where we dropped the kernel mod requirement for shared folders altogether, I've tested with 4.1.9 and works fine, 4.2 should be ok as well.

**Comment by phusl** [comment]
@tianon, I've test `xe-guest-utilities` with kernel 4.1.6 and works fine, and 4.2 should be ok as well.

**Comment by frapposelli** [comment]
@tianon see #1054 for the OVT 10 PR

**Comment by SvenDowideit** [comment]
I vote for 4.2 :)

**Comment by tianon** [comment]
Nice, thanks for the input/testing! :heart:  Since 4.1 is "stable" and 4.2 has some minor issues the Parallels guys are working on, I think we'll go with 4.1 for now and upgrade to 4.2 ASAP.

@legal90 would you mind giving me a sharp poke when you folks have 4.2 support up and going so we can switch over at that point? :+1:

**Comment by legal90** [comment]
@tianon Sure! I will let you know.

**Comment by legal90** [comment]
@tianon By the way, I've noticed that AUFS for 4.2 is not ready yet:
https://github.com/sfjro/aufs4-standalone/tree/aufs4.x-rcN
http://sourceforge.net/p/aufs/support-requests/6/
Is that a show-stopper for boot2docker?

**Comment by tianon** [comment]
Ah, really good find; that's a problem for us too, yeah. :+1:

**Pull request merged**
