### PR TITLE
Add support for the Open vSwitch Kernel Module

### PR DESCRIPTION
**Pull request by dave-tucker**
This PR adds support for the Open vSwitch, VXLAN and GRE kernel modules.
As they are modules, one must `modprobe openvswitch` in order to use them
Our use case is for the `socketplane/docker-ovs` container but others may find these modules useful for anything networking related.

### CODE REVIEW

**Comment by tianon** [comment]
Isn't this a dup of #733?

**Comment by dave-tucker** [comment]
@tianon oops... I didn't see #733, but it's missing the VXLAN and GRE modules that OVS depends on

**Comment by dave-tucker** [comment]
As an addendum, this doesn't seem to increase the `boot2docker.iso` size...  which is cool.

**Comment by tianon** [comment]
Ah, that could actually sway me.  Mind providing a before and after size
comparison?

**Comment by dave-tucker** [comment]
@tianon

```
-rw-r--r--   1 dave  staff  24117248 22 Jan 00:22 boot2docker.iso
-rw-r-----@  1 dave  staff  24117248 13 Feb 23:51 boot2docker.iso.orig
```

**Comment by dave-tucker** [comment]
@nickethier I didn't see your PR before I pushed this.
Would you like to include the VXLAN and GRE modules in your change, or should we just proceed with this one. I have no preference..  I'd just rather not have to keep booting from a custom iso :smile:

**Comment by dave-tucker** [comment]
Final update, for those who might not believe that the iso size is unchanged....

```bash
boot2docker info
{
    "Name": "boot2docker-vm",
    "UUID": "dba70296-1339-4783-a9bf-2dddc8274a03",
    "Iso": "/Users/dave/dev/boot2docker/boot2docker.iso",
    "State": "running",
    "CPUs": 8,
    "Memory": 2048,
    "VRAM": 8,
    "CfgFile": "/Users/dave/VirtualBox VMs/boot2docker-vm/boot2docker-vm.vbox",
    "BaseFolder": "/Users/dave/VirtualBox VMs/boot2docker-vm",
    "OSType": "",
    "Flag": 0,
    "BootOrder": null,
    "DockerPort": 0,
    "SSHPort": 2022,
    "SerialFile": "/Users/dave/.boot2docker/boot2docker-vm.sock"
}%

boot2docker ssh
                        ##        .
                  ## ## ##       ==
               ## ## ## ##      ===
           /""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
           \______ o          __/
             \    \        __/
              \____\______/
 _                 _   ____     _            _
| |__   ___   ___ | |_|___ \ __| | ___   ___| | _____ _ __
| '_ \ / _ \ / _ \| __| __) / _` |/ _ \ / __| |/ / _ \ '__|
| |_) | (_) | (_) | |_ / __/ (_| | (_) | (__|   <  __/ |
|_.__/ \___/ \___/ \__|_____\__,_|\___/ \___|_|\_\___|_|
Boot2Docker version 1.4.1, build openvswitch : 1c620f6 - Thu Jan 22 00:21:10 UTC 2015
Docker version 1.4.1, build 5bc2ff8
docker@boot2docker:~$ modprobe openvswitch
docker@boot2docker:~$ lsmod
Module                  Size  Used by    Tainted: G
openvswitch            49152  0
gre                    12288  1 openvswitch
vxlan                  28672  1 openvswitch
veth                   12288  0
xt_addrtype            12288  2
xt_conntrack           12288  1
ipt_MASQUERADE         12288  1
iptable_nat            12288  1
nf_conntrack_ipv4      16384  2
nf_defrag_ipv4         12288  1 nf_conntrack_ipv4
nf_nat_ipv4            12288  1 iptable_nat
nf_nat                 16384  3 ipt_MASQUERADE,iptable_nat,nf_nat_ipv4
nf_conntrack           57344  6 xt_conntrack,ipt_MASQUERADE,iptable_nat,nf_conntrack_ipv4,nf_nat_ipv4,nf_nat
bridge                 61440  0
stp                    12288  1 bridge
llc                    12288  2 bridge,stp
ipv6                  229376 49 bridge,[permanent]
vboxsf                 28672  1
cpufreq_stats          12288  0
cpufreq_powersave      12288  0
cpufreq_userspace      12288  0
cpufreq_conservative    12288  0
squashfs               28672  0
loop                   20480  1
ppdev                  12288  0
parport_pc             24576  0
parport                28672  2 ppdev,parport_pc
battery                12288  0
pcspkr                 12288  0
ac                     12288  0
i2c_piix4              12288  0
intel_agp              12288  0
vboxguest             139264  1 vboxsf
intel_gtt              16384  1 intel_agp
agpgart                28672  2 intel_agp,intel_gtt
```

**Comment by nickethier** [comment]
I'll push those to this PR tonight

**Comment by nickethier** [comment]
Rather my PR. Either that or merge this one, I don't care either way :)

**Comment by nickethier** [comment]
@tianon I'll echo @dave-tucker in that I saw no size increase with this iso.

**Comment by tianon** [comment]
Yeesh, yeah.  I'll be honest -- I didn't fully believe you and had to test for myself to be sure.  This is some serious voodoo.  :+1:

**Comment by tianon** [comment]
You guys work out which PR wins, and I'll LGTM and merge. :wink:

**Comment by nickethier** [comment]
Dave wins this one :+1:

**Comment by tianon** [comment]
LGTM

**Pull request merged**
