### PR TITLE
Add "CONFIG_VMXNET3" (vmware ethernet driver)

### LINKED ISSUE #1340: driver vmwarefusion: Error creating machine: IP not found for MAC ... in DHCP leases
On OS X high sierra and on the new mojave (with virtualbox and parallels uninstalled) I am not able to create with docker-machine a boot2docker (v18.09.0-beta3) vm with driver vmwarefusion (or even driver vmware) without these errors:

```
Macs-MacBook-Pro:~ mac$ docker-machine -D create --vmwarefusion-boot2docker-url=/Users/mac/.docker/machine/cache/boot2docker.iso --driver=vmwarefusion vmware-dev
Docker Machine Version:  0.15.0, build b48dc28d
...
(vmware-dev) DBG | executing: /Applications/VMware Fusion.app/Contents/Public/vmrun start /Users/mac/.docker/machine/machines/vmware-dev/vmware-dev.vmx nogui
(vmware-dev) Waiting for VM to come online...
(vmware-dev) DBG | executing: /Applications/VMware Fusion.app/Contents/Public/vmrun list
(vmware-dev) DBG | MAC address in VMX: 00:0c:29:47:b5:db
(vmware-dev) DBG | Trying to find IP address in configuration file: /Library/Preferences/VMware Fusion/vmnet1/dhcpd.conf
(vmware-dev) DBG | Following IPs found map[00:50:56:c0:00:01:172.16.127.1]
(vmware-dev) DBG | Trying to find IP address in configuration file: /Library/Preferences/VMware Fusion/vmnet8/dhcpd.conf
(vmware-dev) DBG | Following IPs found map[00:50:56:c0:00:08:192.168.173.1]
(vmware-dev) DBG | Trying to find IP address in leases file: /var/db/vmware/vmnet-dhcpd-vmnet1.leases
(vmware-dev) DBG | Trying to find IP address in leases file: /var/db/vmware/vmnet-dhcpd-vmnet8.leases
(vmware-dev) DBG | Not there yet 1/60, error: IP not found for MAC 00:0c:29:47:b5:db in DHCP leases
...
(vmware-dev) DBG | Not there yet 60/60, error: IP not found for MAC 00:0c:29:47:b5:db in DHCP leases
Error creating machine: Error in driver during machine creation: Machine didn't return an IP after 120 seconds, aborting
```

```
Macs-MacBook-Pro:cache mac$ docker-machine ls
NAME          ACTIVE   DRIVER         STATE     URL   SWARM   DOCKER    ERRORS
vmware-dev    *        vmwarefusion   Running                 Unknown   IP not found for MAC 00:0c:29:47:b5:db in DHCP leases
```

On https://github.com/machine-drivers/docker-machine-driver-xhyve/issues/9 I found : 
https://github.com/machine-drivers/docker-machine-driver-xhyve/issues/9#issuecomment-307221330 (and the following comments).
I tried to to forcefully start bootpd.plist but that didn't work.
For some reason docker-machine on my macbook with driver vmwarefusion does not get or does not request an IP address for the new vm.
In the VM I am thus not able to access the internet.
Normal VM's like CentOS are able to access the internet.
The boot2docker VM's I created with virtualbox driver could access internet but virtualbox VM's do not have CPU acceleration.

### PR DESCRIPTION
**Pull request by tianon**
Closes #1340

### CODE REVIEW

**Comment by StefanScherer** [comment]
@tianon I've tried to build it locally, but I get the same error as Travis https://travis-ci.org/boot2docker/boot2docker/builds/454166287#L1431

**Comment by StefanScherer** [comment]
I've built a boot2docker.iso with that vmxnet3 kernel module and tried it with VMware Fusion 11.0.1 with docker-machine 0.15.0 from Docker for Mac 18.06.1.

```
$ docker-machine create -d vmwarefusion --vmwarefusion-boot2docker-url=./boot2docker.iso test
Running pre-create checks...
(test) Boot2Docker URL was explicitly set to "./boot2docker.iso" at create time, so Docker Machine cannot upgrade this machine to the latest version.
Creating machine...
(test) Boot2Docker URL was explicitly set to "./boot2docker.iso" at create time, so Docker Machine cannot upgrade this machine to the latest version.
(test) Downloading /Users/stefan/.docker/machine/cache/boot2docker.iso from ./boot2docker.iso...
(test) Creating SSH key...
(test) Creating VM...
(test) Creating disk '/Users/stefan/.docker/machine/machines/test/test.vmdk'
(test) Virtual disk creation successful.
(test) Starting test...
(test) Waiting for VM to come online...
Error creating machine: Error in driver during machine creation: exit status 255
```

and with the debug output:

```
docker-machine -D create -d vmwarefusion --vmwarefusion-boot2docker-url=./boot2docker.iso test2
...
(test2) DBG | Trying to find IP address in leases file: /var/db/vmware/vmnet-dhcpd-vmnet1.leases
(test2) DBG | Trying to find IP address in leases file: /var/db/vmware/vmnet-dhcpd-vmnet2.leases
(test2) DBG | Trying to find IP address in leases file: /var/db/vmware/vmnet-dhcpd-vmnet3.leases
(test2) DBG | Trying to find IP address in leases file: /var/db/vmware/vmnet-dhcpd-vmnet8.leases
(test2) DBG | IP found in DHCP lease table: 192.168.65.132
(test2) DBG | Got an ip: 192.168.65.132
(test2) DBG | Creating Tar key bundle...
(test2) DBG | executing: /Applications/VMware Fusion.app/Contents/Public/vmrun -gu docker -gp tcuser directoryExistsInGuest /Users/stefan/.docker/machine/machines/test2/test2.vmx /var/lib/boot2docker
(test2) DBG | executing: /Applications/VMware Fusion.app/Contents/Public/vmrun -gu docker -gp tcuser CopyFileFromHostToGuest /Users/stefan/.docker/machine/machines/test2/test2.vmx /Users/stefan/.docker/machine/machines/test2/userdata.tar /home/docker/userdata.tar
(test2) DBG | executing: /Applications/VMware Fusion.app/Contents/Public/vmrun -gu docker -gp tcuser runScriptInGuest /Users/stefan/.docker/machine/machines/test2/test2.vmx /bin/sh sudo sh -c "tar xvf /home/docker/userdata.tar -C /home/docker > /var/log/userdata.log 2>&1 && chown -R docker:staff /home/docker"
(test2) DBG | executing: /Applications/VMware Fusion.app/Contents/Public/vmrun -gu docker -gp tcuser runScriptInGuest /Users/stefan/.docker/machine/machines/test2/test2.vmx /bin/sh sudo /bin/mv /home/docker/userdata.tar /var/lib/boot2docker/userdata.tar
(test2) DBG | executing: /Applications/VMware Fusion.app/Contents/Public/vmrun -gu docker -gp tcuser enableSharedFolders /Users/stefan/.docker/machine/machines/test2/test2.vmx
Error creating machine: Error in driver during machine creation: exit status 255
notifying bugsnag: [Error creating machine: Error in driver during machine creation: exit status 255]
```

I can ssh into the docker machine

```
$ docker-machine ssh test2
   ( '>')
  /) TC (\   Core is distributed with ABSOLUTELY NO WARRANTY.
 (/-_--_-\)           www.tinycorelinux.net

docker@boot2docker:~$ lsmod
Module                  Size  Used by    Tainted: G  
ipt_MASQUERADE         16384  1 
nf_nat_masquerade_ipv4    16384  1 ipt_MASQUERADE
xfrm_user              32768  1 
iptable_nat            16384  1 
nf_nat_ipv4            16384  1 iptable_nat
xt_addrtype            16384  2 
iptable_filter         16384  1 
xt_conntrack           16384  1 
nf_nat                 24576  2 nf_nat_masquerade_ipv4,nf_nat_ipv4
br_netfilter           20480  0 
bridge                106496  1 br_netfilter
stp                    16384  1 bridge
llc                    16384  2 bridge,stp
overlay                61440  0 
vmxnet3                45056  0 
docker@boot2docker:~$ df -h
Filesystem                Size      Used Available Use% Mounted on
tmpfs                   890.4M    225.4M    665.0M  25% /
tmpfs                   494.7M         0    494.7M   0% /dev/shm
cgroup                  494.7M         0    494.7M   0% /sys/fs/cgroup
tmpfs                   890.4M    225.4M    665.0M  25% /var/lib/docker
```

Inside the docker machine I can pull and run images, but VMware shared folder doesn't seem to work.

I have also tried to build a 18.06.1 docker machine and have slight problems at least with shared volumes as well. I'll try the 18.09.0 boot2docker.iso tomorrow on another Mac with VMware Fusion 10.x.x and see if it works there.

**Comment by tianon** [comment]
Hmm, I wonder if we need `CONFIG_VMWARE_VMCI` for the shared folders -- mind adding `CONFIG_VMWARE_VMCI=m` to this `files/kernel-config.d/vmware` file too and doing a re-test?

**Comment by MartinSGill** [comment]
Tested it in Worksation Pro 15, on Win 10

**`vmware` driver**
```
dm create -d vmware --vmware-boot2docker-url=https://github.com/StefanScherer/boot2docker/releases/download/v18.09.0-vmxnet3/boot2docker.iso vmware
Running pre-create checks...
(vmware) Boot2Docker URL was explicitly set to "https://github.com/StefanScherer/boot2docker/releases/download/v18.09.0-vmxnet3/boot2docker.iso" at create time, so Docker Machine cannot upgrade this machine to the latest version.
Creating machine...
(vmware) Boot2Docker URL was explicitly set to "https://github.com/StefanScherer/boot2docker/releases/download/v18.09.0-vmxnet3/boot2docker.iso" at create time, so Docker Machine cannot upgrade this machine to the latest version.
(vmware) Downloading C:\Users\mgill\.docker\machine\cache\boot2docker.iso from https://github.com/StefanScherer/boot2docker/releases/download/v18.09.0-vmxnet3/boot2docker.iso...
(vmware) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
(vmware) Creating SSH key...
(vmware) Creating VM...
(vmware) Starting vmware...
(vmware) Waiting for VM to come online...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with boot2docker...
Error creating machine: Error running provisioning: Unable to verify the Docker daemon is listening: Maximum number of retries (10) exceeded
```

**`vmwareworkstation` driver**
```
dm create -d vmwareworkstation --vmwareworkstation-boot2docker-url=https://github.com/StefanScherer/boot2docker/releases/download/v18.09.0-vmxnet3/boot2docker.iso vmwarews
Running pre-create checks...
(vmwarews) Boot2Docker URL was explicitly set to "https://github.com/StefanScherer/boot2docker/releases/download/v18.09.0-vmxnet3/boot2docker.iso" at create time, so Docker Machine cannot upgrade this machine to the latest version.
Creating machine...
(vmwarews) Boot2Docker URL was explicitly set to "https://github.com/StefanScherer/boot2docker/releases/download/v18.09.0-vmxnet3/boot2docker.iso" at create time, so Docker Machine cannot upgrade this machine to the latest version.
(vmwarews) Downloading C:\Users\mgill\.docker\machine\cache\boot2docker.iso from https://github.com/StefanScherer/boot2docker/releases/download/v18.09.0-vmxnet3/boot2docker.iso...
(vmwarews) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
(vmwarews) Creating SSH key...
(vmwarews) Creating VM...
(vmwarews) Creating disk 'C:\Users\mgill\.docker\machine\machines\vmwarews\vmwarews.vmdk'
(vmwarews) Virtual disk creation successful.
(vmwarews) Starting vmwarews...
(vmwarews) Waiting for VM to come online...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with boot2docker...
Error creating machine: Error running provisioning: Unable to verify the Docker daemon is listening: Maximum number of retries (10) exceeded
```

**Notes**

Logging into the VM directly I see that eth0 is present and has the expected IP.
Docker appears to be running
Just as Stefan I can ssh to the machine:
```
dm ssh vmwarews
   ( '>')   ( '>')
  /) TC (\   Core is distributed with ABSOLUTELY NO WARRANTY.
 (/-_--_-\)           www.tinycorelinux.net

docker@vmwarews:~$ docker system info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 18.09.0
Storage Driver: overlay2
 Backing Filesystem: tmpfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.79-boot2docker
Operating System: Boot2Docker 18.09.0 (TCL 8.2.1)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 989.3MiB
Name: vmwarews
ID: M7A7:EE7A:TD5T:AS7V:VZ6F:XNG7:U2GS:XDR5:XP4R:2INP:SRP4:YCOS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

**Comment by StefanScherer** [comment]
After dozens of tries with different versions of macOS, Fusion, docker-machine binaries, boot2docker.iso's I got following news.

- The `docker-machine` **0.13.0** binary for macOS seems the last one that works for the `vmwarefusion` driver. I can create docker machines up to 18.06.1 with it on nearly any macOS (10.12, 10.13.2, 10.14.1, only 10.14 didn't work) I got, and VMware Fusion 8.5.8, 10.1.4, 11.0.1.
- From `docker-machine` 0.14.0 on (also tested with 0.15.0, 0.16.0) I get errors at the vmrun enableSharedFolders call.

The modified boot2docker.iso of this PR with vmxnet3 and the vmci modules can enable the shared folders without an error, but there is still no /Users folder mounted from the host in the VM.
And then there is another error where the `docker-machine` 0.13.0 binary aborts after 10 retries in a `netstat -tln` loop looking for the Docker engine port 2376. The full debug output is in [this gist](https://gist.github.com/StefanScherer/06b8a131d63f6841d74d5f420796c5a5#file-docker-machine-0-13-0-b2d-18-09-0-vmxnet3-vmci-fusion-10-1-3-macos-10-14-1-txt).
The [lines 152-154 of the gist](https://gist.github.com/StefanScherer/06b8a131d63f6841d74d5f420796c5a5#file-docker-machine-0-13-0-b2d-18-09-0-vmxnet3-vmci-fusion-10-1-3-macos-10-14-1-txt-L152-L154) may be of interest.

A quick check of the docker machine for the shared folder can be done with
```
$ docker-machine ssh test ls /Users
```

**Comment by lunetics** [comment]
I'm using the vmwarevsphere driver and get the same error as  @MartinSGill 
With the patched vmxnet3 version from @StefanScherer it'll go to the provision step, before it froze at `Waiting for VMware Tools to come online...`

```
Running pre-create checks...
Creating machine...
(testdockermachine) Boot2Docker URL was explicitly set to "https://github.com/StefanScherer/boot2docker/releases/download/v18.09.0-vmxnet3-vmci/boot2docker.iso" at create time, so Docker Machine cannot upgrade this machine to the latest version.
(testdockermachine) Downloading /root/.docker/machine/cache/boot2docker.iso from https://github.com/StefanScherer/boot2docker/releases/download/v18.09.0-vmxnet3-vmci/boot2docker.iso...
(testdockermachine) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
(testdockermachine) Generating SSH Keypair...
(testdockermachine) Creating VM...
(testdockermachine) Uploading Boot2docker ISO ...
(testdockermachine) adding network: VM Network
(testdockermachine) Reconfiguring VM
(testdockermachine) Waiting for VMware Tools to come online...
(testdockermachine) Provisioning certs and ssh keys...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with boot2docker...
Error creating machine: Error running provisioning: Unable to verify the Docker daemon is listening: Maximum number of retries (10) exceeded
```

**Comment by lunetics** [comment]
Addition. Testing with boot2docker v18.06.1-ce worked fine so far, `netstat -tln` gives the correct output with the docker ports:
```
netstat -tln
SSH cmd err, output: <nil>: Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      
tcp        0      0 :::2376                 :::*                    LISTEN      
tcp        0      0 :::22                   :::*                    LISTEN      
```

**Comment by StefanScherer** [comment]
Thanks @lunetics this seems the same problem. Before docker-machine inserts the TLS certs it expects the Docker engine running and listening on port 2376.
The docker-machine provisioner checks up to 10 times with [`WaitForDocker` and `checkDaemonUp`](https://github.com/docker/machine/blob/821e8c76f048ca9323ecc9440c0e3d3d5ec4906d/libmachine/provision/utils.go#L254-L274) if port 2376 is listening. For boot2docker running in VMware this is not the case and docker-machine then gives up.

For some reason using the `virtualbox` driver there are TLS certs even in the 18.09.0 ISO and docker starts listening on port 2376.
For `vmwarefusion` the tls folder keeps empty and therefore the `checkDaemonUp` never succeeds.

Previous versions of boot2docker.iso automatically created some certs so Docker engine was always (vmwarefusion and virtualbox) running and listening on port 2376 so the provisioning was continued.


I currently struggle at the point that newer docker-machine binaries abort at `vmrun enableSharedFolders` where the version 0.13.0 worked without an error. I can't see where the difference is.
```
(test2) DBG | executing: /Applications/VMware Fusion.app/Contents/Public/vmrun -gu docker -gp tcuser enableSharedFolders /Users/stefan/.docker/machine/machines/test2/test2.vmx
Error creating machine: Error in driver during machine creation: exit status 255
notifying bugsnag: [Error creating machine: Error in driver during machine creation: exit status 255]
```

The docker-machine binary inserts a `userdata.tar` file to `/var/lib/boot2docker` but with only the SSH key pair and not already the TLS certs. Maybe this behaviour is different to the virtualbox driver?

```
$ tar tvf userdata.tar 
----------  0 0      0          36 Jan  1  1970 boot2docker, this is vmware speaking
drwx------  0 0      0           0 Jan  1  1970 .ssh
-rw-r--r--  0 0      0         381 Jan  1  1970 .ssh/authorized_keys
-rw-r--r--  0 0      0         381 Jan  1  1970 .ssh/authorized_keys2
```

**Comment by StefanScherer** [comment]
OK, learn a bit from reading the source. docker-machine 0.13.0 just didn't check the return code of vmrun enableSharedFolders, so with the 18.09.0 ISO it does not abort here, but no shared folder is mounted. We have to check how to make the vmtools work and talk with VMware hypervisor.

And there is a timing issue with the userdata.tar file when it gets copied into the VM and when the [/etc/init.d/docker script](https://github.com/boot2docker/boot2docker/blob/4034f1f588f4a7221f1d58502463fd4f91b52b9b/files/init.d/docker#L17-L21) checks for it to create some dummy certs to start docker listening on 2376 for further provisioning.

**Comment by tianon** [comment]
Ok, this is updated now.  I have personally tested this via:

- VMware Fusion 15 (trial)
- https://github.com/docker/machine/releases/tag/v0.16.0
- https://github.com/machine-drivers/docker-machine-driver-vmware/releases/tag/v0.1.0

Shared folders are working, but not mounting at `/Users` which is odd -- they're going to `/hosthome` (so `/hosthome/tianon` shows my home directory contents successfully :+1:).

**Comment by tianon** [comment]
The following was in the logs:
`(default) DBG | executing: /Applications/VMware Fusion.app/Contents/Public/vmrun -gu docker -gp tcuser runScriptInGuest /Users/tianon/.docker/machine/machines/default/default.vmx /bin/sh [ ! -d /hosthome ]&& sudo mkdir /hosthome; sudo mount --bind /mnt/hgfs//hosthome /hosthome || [ -f /usr/local/bin/vmhgfs-fuse ]&& sudo /usr/local/bin/vmhgfs-fuse -o allow_other .host:/Users /hosthome || sudo mount -t vmhgfs -o uid=$(id -u),gid=$(id -g) .host:/Users /hosthome`

(Which explains `/hosthome`.)

**Comment by StefanScherer** [comment]
Thanks @tianon I can reproduce your results. 🎉 
- With docker-machine 0.16.0 and the built-in `vmwarefusion` driver it still aborts due to the error checks at vmrun enableSharedFolders.
- With docker-machine 0.16.0 and the additional `vmware` driver 0.1.0 I can create a Docker machine and the shared folder mounted at `/hosthome` instead of `/Users`.

**Comment by lunetics** [comment]
@StefanScherer should we open another ticket on the wrong / missing netstat output (to detect if docker is running?)

**Pull request merged**
