### PR TITLE
Update kernel to 4.4.7

### PR DESCRIPTION
**Pull request by tianon**
See also https://github.com/docker/machine/issues/3327#issuecomment-211606359 (and following discussion)

cc @nathanleclaire

### CODE REVIEW

**Comment by nathanleclaire** [comment]
lgtm

**Comment by tianon** [comment]
I'm building this now so that I can verify that it actually works, and so that I can update `kernel_config` with the result of `make oldconfig` too. :+1:

**Comment by tianon** [comment]
cc @frapposelli @legal90 @phusl -- anything objections to making this move? Any additional changes we'll need to make that you're aware of?

**Comment by frapposelli** [comment]
gif-keyboard-10579270890393958576

**Comment by legal90** [comment]
@tianon I've verified it with Parallels Tools 11.1.0 - everything works fine. LGTM

**Comment by nathanleclaire** [comment]
If Keanu approves then you know it's good.

**Comment by tianon** [comment]
Ok, new commit applies defaults from `make oldconfig` (except `CONFIG_CGROUP_PIDS`, which I noticed and set to `y` because https://github.com/docker/docker/pull/18697 which is part of Docker 1.11 :balloon:)

**Comment by tianon** [comment]
```console
docker@boot2docker:~$ docker run -it --rm --pids-limit 1 alpine:3.3 sh
/ # ls -l
sh: can't fork
/ # 
```

image

**Comment by nathanleclaire** [comment]
Hahaha... I'm not sure the relevance of Professor Quirrel, but supporting `--pids-limit` is good right?

**Comment by nathanleclaire** [comment]
On older VM it complains to me.

```console
docker@default:~$ docker run -ti --rm --pids-limit 1 alpine sh
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine
420890c9e918: Pull complete
Digest: sha256:9cacb71397b640eca97488cf08582ae4e4068513101088e9f96c9814bfda95e0
Status: Downloaded newer image for alpine:latest
WARNING: Your kernel does not support pids limit capabilities, pids limit discarded.
```

**Comment by nathanleclaire** [comment]
screen shot 2016-04-19 at 2 04 54 pm

**Comment by tianon** [comment]
Ok, merging! :+1:

**Comment by nathanleclaire** [comment]
🎉

**Pull request merged**
