### PR TITLE
Update "docker daemon" to simply "dockerd" ("docker daemon" is officially deprecated in 1.13+)

### PR DESCRIPTION
**Pull request by tianon**
cc @yosifkit @nathanleclaire

See also https://github.com/docker/docker/issues/28368 (`docker daemon` sometimes broken in 1.13.0-rc1)

### CODE REVIEW

**Comment by nathanleclaire** [comment]
LGTM

**Comment by tianon** [comment]
@nathanleclaire did you get a chance to test that ISO I sent over? :pray:

**Comment by tianon** [comment]
(I've run it successfully locally)

**Comment by nathanleclaire** [comment]
I haven't tested but LGTM, this is almost exact same change I made on Machine provisioned servers without issue

**Pull request merged**
